### PR TITLE
add dds support for currentTricks

### PR DESCRIPTION
**Pull request by ed2k**

### CODE REVIEW

**Comment by anntzer** [comment]
Thanks for the suggestion.  I would prefer an API like https://github.com/anntzer/redeal/tree/ct (see https://github.com/anntzer/redeal/commit/14172abc7fbdf840e1a57a35fc58e3f1665d3fdf), what do you think?

**Comment by ed2k** [comment]
to complete (as playable) we need more than currentTrciks. we also need trump and lead
I think trump can be 'CDHSU' and lead could be 'NESW'
https://github.com/ed2k/dds/blob/wasm/examples/dds.cpp
https://ed2k.github.io/dds/test_dds.html
I haven't settle on the actual api

**Comment by anntzer** [comment]
That information is passed via the strain and declarer args.

**Comment by ed2k** [comment]
ah, yes, that looks complete then.

**Comment by anntzer** [comment]
I merged that branch into master.

**Pull request closed without merging**
