### PR TITLE
Added hand functions l1, l2, l3, l4

### PR DESCRIPTION
**Pull request by palamau**
Implemented properties l1, l2, l3 and l4 representing the descending lengths of various suits in a hand as defined in
https://bridge.thomasoandrews.com/deal/advanced.html.  To quote from that url,

```
The pattern of a hand is the lengths of the suits in the hand, sorted in descending order.

You could define the pattern class, "balanced," as:

patterncond balanced {$l1>3 && $l2>=3 && $l3>=3 && $l4>=2}

The variables l1, l2, l3, and l4 are set to the lengths of the suits, l1 being the longest, l4 the shortest.
[For clarification, the first characters of each of those variables is the lowercase letter L.]
```

### CODE REVIEW

**Comment by anntzer** [comment]
These are somewhat obscure, and I think the pythonic way to do it would be to write `l4, l3, l2, l1 = sorted(deal.north.shape)`, which 1) is clearer and 2) is in fact shorter (and more efficient) than repeatedly writing `deal.north.l1`/`deal.north.l2`/etc (as we have no concept of patternclass).  Thoughts?

**Comment by palamau** [comment]
I agree with your observations.  However from a practical point of view, it
is desirable that we provide feature compatibility with what is already
provided by Thomas.   For example, I have  a considerable amount of code
written in TCL which i had been meaning to rewrite using redeal for at
least a couple of years but had put it off since I noticed these "missing"
functions.  It is possible that there could be others like me.

Furthermore a typical way someone may use these is to evaluate whether a
hand fits specific criteria such as

def shapely (h):
    h.l1 >= 6 or h.l4 <= 1


From the point of view of a client of  "redeal" ,  being able to write
concise code like the one shown above does seem like a win.

 Having said that, it might make sense from an efficiency perspective to
compute these values at the time of object creation but we will then have
to make sure that we update these values anytime someone modifies the
object.

As an aside, I also think that i need to add regression tests to make sure
that we do not break anything in the course of making changes

**Comment by anntzer** [comment]
Sure, I added the functionality into main.  Thanks for the suggestion.

**Comment by palamau** [comment]
Hi Antony,

I saw your commit.  Thanks for taking care of this

RG

**Pull request closed without merging**
